### ISSUE TITLE
Piping to xclip is missing

### ISSUE THREAD

**Issue by maximbaz** [laktak/extrakto#1]
> This sample (for tmux 2.4+) defines a extract-mode that you enter with X and then use p to extract paths or u for urls **(piping to xclip)**

I think the `piping to xclip` part was forgotten in the example, and I actually cannot come up a proper syntax to do it myself... Could you help out?

I want to pipe to `xclip -selection clipboard`

**Comment by laktak** [comment]
Not sure why but xclip only works when run in the background. Please try it with the update.

**Comment by maximbaz** [comment]
It works, awesome!

---------------

I'll just dump my feedback and thoughts in here, let me know if you want me to organize them somehow, like in different issues:

1. The piece `send -X cancel \; ` causes troubles for me, every time I press a hotkey, all I see is a message from tmux `Not in a mode`. If I remove this piece from every binding, everything begins to work perfectly. Not sure what it is supposed to do 🙂 I'm on a tmux built from `master` branch maybe a month ago, ArchLinux.

2. Definitely wrap it in a tmux plugin, this thing is awesome! Filtering with fzf is faster than copycat's way of jumping one by one between matches. Ideally I'd not have to download any binaries or put extra bindings in my .tmux.conf, except of only one line `set -g @plugin 'laktak/extrakto'` 🙂

3. Regexes could use some improvements, but this we can definitely take separately.

![image](https://user-images.githubusercontent.com/1177900/30723191-e6d061c4-9f35-11e7-9c14-40af91adb607.png)

4. The script doesn't handle wrapped text very well, like see in the example below the top url suggestion ends with `veee`, although this is not the end of the url.

![image](https://user-images.githubusercontent.com/1177900/30723291-943b6c5a-9f36-11e7-940c-deed15c4296d.png)

**Comment by laktak** [comment]
1. that were some leftovers because I use it from vi mode, sorry
2. have you made any tmux plugins or can you point me to a short sample?
3. and 4. - yes PRs are welcome ;) I tried to find some existing regexes for extracting paths and urls but came up suprisingly short.

**Comment by maximbaz** [comment]
2. No personal experience, but I would suggest to look into [tmux-plugins/tmux-example-plugin](https://github.com/tmux-plugins/tmux-example-plugin) or at some of the existing plugins under [tmux-plugins](https://github.com/tmux-plugins/) account.

3. and 4. Definitely :) But regardless, do release the plugin, the current regexes work acceptably well, if something would feel particularly annoying, I'll submit a PR :)

For future reference, here are the regexes from tmux-copycat itself:

https://github.com/tmux-plugins/tmux-copycat/blob/57ce42387aa70b7b20346a27f582f5ca0239bff2/copycat.tmux#L17-L22

**Comment by maximbaz** [comment]
I'll close the issue since xclip is fixed now 🙂

**Comment by laktak** [comment]
@maximbaz it should now work as a plugin.

**Comment by maximbaz** [comment]
And it works indeed, awesome stuff!
