### ISSUE TITLE
Cursor position defaults as first match

### ISSUE THREAD

**Issue by windowsrefund** [laktak/extrakto#100]
Hello,

Thank you for this excellent plugin. I'm noticing an odd behavior which seems like it may be bug.

![Screenshot_2022-09-04_00-08-58](https://user-images.githubusercontent.com/512222/188296904-ed7d5519-e58c-4105-877d-24eb7a3da656.png)

Notice how that first "match" is actually just the cursor position rather than anything of value? Curious to hear your thoughts.

**Comment by laktak** [comment]
Are you opening extrakto from vim?

I'm not sure what order fzf uses when you don't type anything. But I don't think you can expect "anything of value" unless you type a few characters.
