### ISSUE TITLE
Go to selection option

### ISSUE THREAD

**Issue by hqkhan** [laktak/extrakto#101]
Hello. I'm new to using extrakto and was wondering if there's a way to go to my selection in the terminal. For example, I issue `ctrl+prefix+tab` to activate search, navigate to specific text I'm looking for and press a keybind to have my terminal scroll to that position. Is that possible?

**Comment by laktak** [comment]
It might be possible by putting the selection into the tmux search. 

I'm not sure I understand the use case though. Do you think searching with fzf is better/faster than using tmux search?

**Comment by hqkhan** [comment]
That's a good point. I could put the selection into tmux search. 

I think fuzzy searching would be faster than normal tmux search. While fuzzy searching, I can quickly look at the results as they get filtered and press `<keybind>` on them (probably enter) and it would be awesome to just have the terminal go there in copy mode or something. This will entail taking the selection and passing it as a tmux search option. But you could have duplicate results which would mean that tmux goes to the first selection. 

I'm just spitballing at this point but it could be useful to get a preview window where it shows a few lines around the current selection so you know where to "jump" to.

**Comment by laktak** [comment]
> But you could have duplicate results which would mean that tmux goes to the first selection.

There is no other way. It can't know which selection you want.

I'm not convinced that this would provide a lot of value. If you want to experiment with it, the simplest way is to replace the logic for edit and check if you like the result. In `extrakto/scripts/extrakto.sh` look for `edit_key` and replace `tmux send-keys...` to do a search.

**Comment by hqkhan** [comment]
Thank you for letting me know. Will try if I get the chance. Otherwise, closing for now.
