### ISSUE TITLE
Not copying into the clipboard

### ISSUE THREAD

**Issue by MahdiAghaei1** [laktak/extrakto#104]
This part of my .tmux.conf:
```sh
set -g @plugin 'laktak/extrakto'
set -g @extrakto_clip_tool "xsel -i -b" 
```
Running `echo hi | xsel -i -b` would correctly copy the text to my system clipboard but using the extrakto wouldn't.
I even test it with `xclip -sel clip`, it wouldn't work either.
Also I'm using Ubuntu 22.04.2 LTS and gnome-terminal

**Comment by laktak** [comment]
Some tips: 
- check that env variables are set (like `DISPLAY`)
- try `extrakto_clip_tool_run` with bg or fg

**Comment by MahdiAghaei1** [comment]
Sorry for the late response, I haven't time to try what you suggested because I recently changed my operating system to Arch Linux and everything now looks OK. My original problem was that I could not use `wl-clipboard` because it would somehow make my Neovim unusable, so I was trying to use `xsel` or something else. But on my current operating system using wl-clipboard is fine.

**Comment by MahdiAghaei1** [comment]
Nope, I was wrong my problem with `wl-clipboard` and `Neovim` still  exists and I can't use it. 

I checked and there is no variable called `DISPLAY` what should be its value?
I also tried setting `extrakto_clip_tool_run` to bg or fg along side this setting `set -g @extrakto_clip_tool "xsel --input --clipboard" # works better for nvim` but I still could not copy the text to my clipboard.
