### ISSUE TITLE
Allow custom filters in `@extrakto_filter_order`

### ISSUE THREAD

**Issue by qstrahl** [laktak/extrakto#109]
Pretty much what the title says. I wracked my brain for hours trying to figure out what I was doing wrong only to realize that only `word`, `all`, and `line` are allowed in `@extrakto_filter_order`. I would very much like to be able to cycle through all (or perhaps a select few) of my custom filters as well.

**Comment by laktak** [comment]
Not sure if @marcdeop is still interested - he did fix this in #103 but that PR was too large to merge

**Comment by qstrahl** [comment]
Ah, missed that one - thanks for pointing me in that direction. I'll take a look at the PR and see if I can't pull out the relevant parts

**Comment by marcdeop** [comment]
Hopefully this is fixed (or at least improved) by #111

**Comment by laktak** [comment]
Thanks @marcdeop!

@qstrahl can you test if it works for you?

**Comment by laktak** [comment]
@qstrahl it works now

**Comment by qstrahl** [comment]
@laktak Awesome! Thank you so much, and you too @marcdeop !
