### ISSUE TITLE
Parsing the text sent to EDITOR$

### ISSUE THREAD

**Issue by jgarciaokode** [laktak/extrakto#110]
This is current behaviour

<img width="603" alt="image" src="https://github.com/laktak/extrakto/assets/79897391/3049a119-b18c-4898-9fec-5798f505d7ae">

This is the expected behaviour to make it work

<img width="627" alt="image" src="https://github.com/laktak/extrakto/assets/79897391/953d4fc7-0c90-4a2a-ba11-96d0a70899e1">

This is how it is opened

<img width="640" alt="image" src="https://github.com/laktak/extrakto/assets/79897391/53a41697-959c-4467-9011-4a0edfcbb8af">

**Comment by laktak** [comment]
I think you misunderstood that feature. You are supposed to select a filepath to open in the editor.
