### ISSUE TITLE
extrakto.py: error: argument -a/--add: expected one argument

### ISSUE THREAD

**Issue by JiyuFang-git** [laktak/extrakto#112]
Hi there,

I did not define my own filter and I leave [extrakto.conf ](https://github.com/laktak/extrakto/blob/master/extrakto.conf)as it is.

I'm not setting @extrakto_filter_order either.

But when l start extrakto its always reporting:
extrakto.py: error: argument -a/--add: expected one argument

and I'm seeing ^f=filter[] (aka the filter field is empty)

**Comment by JiyuFang-git** [comment]
ok I think the issue is coming from helpers.sh
![6601703823671_ pic](https://github.com/laktak/extrakto/assets/24462863/cb60a803-4115-4d9a-baef-f42256631efb)

I changed line 149 to 
`readarray -t  modes_list <<< "$(get_option @extrakto_filter_order) "`

and it works like a charm

could this have sth to do with my bash version?
```
$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
```

**Comment by laktak** [comment]
Yes, it's listed in the README. Also see https://github.com/laktak/extrakto/wiki/Bash4
