### ISSUE TITLE
Support `fzf-tmux`

### ISSUE THREAD

**Issue by liangkarl** [laktak/extrakto#115]
Hi Laktak,

I use this tool for a period of time. I have a window-spliting problem while using it in a zoomed window. `extrakto` would 
zoom out the window and split a new one to for `fzf`, which always mess up the original layout and sometimes make me lose the focus point due to looking for the correct pane. As `fzf` already provide a small wrapper tool for tmux that is `fzf-tmux` which has a better behaviour in this case without zoomed out the window and mess up the layout. Could you help to support it?

Thanks!

**Comment by laktak** [comment]
extrakto uses popups, this keeps the zoom state the same:

> [tmux](https://github.com/tmux/tmux) - popups require 3.2, otherwise extrakto will open in a split window.

Are you on an old tmux?

**Comment by liangkarl** [comment]
Uh, no...
I'm using tmux `3.3a` and `3.4`

However, as you said, the popup window would not bother the zoomed window, but the split window did.
It's easy to reproduce that simply change between the two values in a zoomed window,
`set -g @extrakto_split_direction 'v'`
and
`set -g @extrakto_split_direction 'p'`

Also, if we try to use `ls | fzf-tmux` in a zoomed window, `fzf-tmux` would keep the zoom state.

**Comment by laktak** [comment]
In that case it is working as expected. Please use the popup window.

**Comment by laktak** [comment]
vertical split has other drawbacks, that's why we switched to popups by default.

fzf doesn't want to do horz scrolling either https://github.com/junegunn/fzf/issues/577
