### ISSUE TITLE
Show only the filter type at key hint

### ISSUE THREAD

**Issue by uimataso** [laktak/extrakto#116]
Hi! First of all, thanks for your effort put into making this plugin! This is the best tmux copy plugin I have used so far!

But, the only issue I have is that when I have the terminal half screen, the key hint (fzf header) area becomes too small to see what the filter type is currently on.

Can I have a key hint that only shows the filter type?

**Comment by laktak** [comment]
I added an option for you. See `@extrakto_fzf_header` in the README.

**Comment by laktak** [comment]
I don't use nix so I have no idea but if you want to share any tips there is the wiki: https://github.com/laktak/extrakto/wiki

**Comment by uimataso** [comment]
I will, if I have anything valuable :).
