### ISSUE TITLE
Create Extrakto screencast

### ISSUE THREAD

**Issue by ivanalejandro0** [laktak/extrakto#12]
Other tmux plugins ([tmux-yank](https://github.com/tmux-plugins/tmux-yank), [tmux-copycat](https://github.com/tmux-plugins/tmux-copycat)) have screencasts that catches people's attention into using them.

It would be really nice to have something like that for Extrakto.

And (maybe to be handled as a different issue) we could consider having some short gifs to quickly show potential users how cool Extrakto is :)

**Comment by laktak** [comment]
Good idea - maybe do your PR first so we have the latest UI?

**Comment by laktak** [comment]
What do you think about this one? ([README](https://github.com/laktak/extrakto/blob/master/README.md))

**Comment by ivanalejandro0** [comment]
Oh, looks good :)

I can't tell what's missing on your recording, though.
I've used Giphy on OSX and a friend of mine recommended me peek for Linux, but I don't know if any of those will solve the problem you're having.

**Comment by laktak** [comment]
I fixed it for now but I'll look into those if I ever have to do it again ;) I was using Videogif ... found a workaround.

**Comment by ivanalejandro0** [comment]
Oh, I see what you mean now. Those overlays are useful. Great job.
I'd say that you can close this issue now. If eventually this needs improvement then that's a task for another issue.
