### ISSUE TITLE
open.sh returned 1

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [laktak/extrakto#120]
I am running tmux v3.2a and have installed extrakto via tpm.

When I do "C-b TAB" I get: 

```
'"/home/myuser/.tmux/plugins/extrakto/scripts/open.sh" "%6"' returned 1 
```

Any Idea what this could be or how I could debug this? 
Thanks!

**Comment by laktak** [comment]
Do you have the latest version installed? I thought I fixed that yesterday.

Otherwise run the open command with that parameter in a terminal.

**Comment by RudolfVonKrugstein** [comment]
I updated and it works. Great, thanks!
