### ISSUE TITLE
Error with ctrl-g after setting a different key to @extrakto_grab_key

### ISSUE THREAD

**Issue by elgoog** [laktak/extrakto#121]
Error with ctrl-g after unsetting from @extrakto_grab_key
I set ctrl-s for @extrakto_grab_key:

`set -g @extrakto_grab_key "ctrl-s"`

After that, ctrl-s works well. However, ctrl-g invokes the following error:

```
not enough values to unpack (expected at least 2, got 0)
error: unable to extract - check/report errors above
You can also set the fzf path in options (see readme).
```

**Comment by laktak** [comment]
For some reason fzf treats `ctrl-g` like `ctrl-c` if it's not assigned as a key. I'll fix it.

**Comment by elgoog** [comment]
Thank you for the prompt fix! I have confirmed that it is functioning correctly.
