### ISSUE TITLE
insert and copy not working with filter "all"

### ISSUE THREAD

**Issue by bevicted** [laktak/extrakto#122]
Tested on both OSX and GNU/Linux, with same results.

## OSX

```
❯ /usr/bin/env bash --version
GNU bash, version 5.2.26(1)-release (x86_64-apple-darwin23.2.0)
...
❯ tmux -V
tmux 3.4
```

| filter | insert | copy |
| - | - | - |
| word | inserts | copies |
| all | pastes from clipboard | does nothing |
| line | inserts | copies |

## GNU/Linux

```
❯ /usr/bin/env bash --version
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)
...
❯ tmux -V
tmux 3.4
```

| filter | insert | copy |
| - | - | - |
| word | inserts | copies |
| all | pastes from clipboard | does nothing |
| line | inserts | copies |

---

I've rebound my keys to `ctrl-y` to copy and `enter` to insert, so I thought I'd also do these tests without touching any configs of extrakto.
Same results, except interestingly, initially with the `all` filter insert did nothing and copy cleared my clipboard, until I copied something with the `word` filter, then it went back to the behaviour in the tables above.

**Comment by laktak** [comment]
Thank you for catching this and for your detailed bug report! It should be fixed now.

**Comment by bevicted** [comment]
Just tested it out on both platforms and it's working like a charm!

Thanks for the quick fix and super useful tool.
