### ISSUE TITLE
'tmux show-buffer|clip.exe' returned 127 in WSL

### ISSUE THREAD

**Issue by rpop0** [laktak/extrakto#125]
Hello,

So I already fixed this but I'm making this issue in case anyone else comes across this and needs a fix. Essentially, this error happens when you try to use extrakto in WSL when you have the **'appendWindowsPath'** in option /etc/conf.wsl set to false.

I had some issues with my shell being slow and removing all the Windows paths from WSL fixed the issue, but in turn, executables like **clip.exe** were no longer directly accessible.

I sloved this issue by creating a symlink to /mnt/c/Windows/System32/clip.exe in my ~/.local/bin, but this can probably be avoided by using clip.exe's absolute path directly.

**Comment by laktak** [comment]
> I sloved this issue by creating a symlink to /mnt/c/Windows/System32/clip.exe in my ~/.local/bin, but this can probably be avoided by using clip.exe's absolute path directly.

You can configure this with `@extrakto_clip_tool` as well. But having it handled automatically would be better of course :)

**Comment by laktak** [comment]
I merged it, thank you!
