### ISSUE TITLE
How should I change the color?

### ISSUE THREAD

**Issue by zrquan** [laktak/extrakto#127]
My fzf uses the [Catppuccin](https://github.com/catppuccin/fzf) color scheme:
```
export FZF_DEFAULT_OPTS=" \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#b7bdf8,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796 \
--color=selected-bg:#494d64 \
--multi"
```

Then I set `@extrakto_fzf_unset_default_opts` to `false`, but the Catppuccin color scheme didn’t take effect.

**Comment by laktak** [comment]
If you set `@extrakto_fzf_unset_default_opts` to false the FZF_DEFAULT_OPTS will be kept. You need to set them before starting tmux however.

**Comment by zrquan** [comment]
> You need to set them before starting tmux however.

I set FZF_DEFAULT_OPTS in `.zshrc`. It should execute earlier than tmux, right?

**Comment by laktak** [comment]
As it's your system you'll need to debug it yourself, sorry but I can't help you there.

As a workaround you could use a script where you set your options with @extrakto_fzf_tool
