### ISSUE TITLE
extrakto_filter_order "all" doesn't include "line" or "word"

### ISSUE THREAD

**Issue by CharlesARoy** [laktak/extrakto#129]
The documentation for extrakto_filter_order states that `all applies all filters at the same time` but the filters "word" and "line" aren't actually included in mode "all". I think that a filter mode without word is a good thing because it would be hard to narrow the results down if all words were included.

That said, I'd kind of like a mode that includes all filters except words... (i.e. "all_with_lines"). If the lines could be prepended with "line: " in the same way that other filters are indicated (e.g. "s-quote: ") then I could quickly narrow down the results to just lines by typing "line" in my fzf search.

**Comment by laktak** [comment]
I've updated the help and included an example how you can do this:

https://github.com/laktak/extrakto/blob/c259de580fae5a0bc54867b80556dbe50b859be1/extrakto.conf#L61-L65

give it a try

**Comment by CharlesARoy** [comment]
Thanks @laktak! That did exactly what I wanted.

**Comment by CharlesARoy** [comment]
Oh, actually, I'm not sure why this is happening, but in "all" mode with line included, I'm only seeing 20 or so lines from the history and they don't seem to sorted in any discernable order.

By contrast, when I switch over to the line only mode, I see all lines from the available history in order of their appearance on screen (new to old). Is there something about the regex pattern you shared that differs from the one used in line mode?

**Comment by laktak** [comment]
Like it says in the note above, line mode is different.

It seems I made a mistake when filtering out whitespace at the end of the line, please test this regex:

```
[line] 
regex: ([^\n\r]+?)\s*\r?\n
```

**Comment by Charles-Alexandre-Roy** [comment]
Thanks @laktak! With that change, the behavior of line mode added to all mode seems to duplicate that of line mode on its own. At least, it does exactly what I want.

**Comment by CharlesARoy** [comment]
Thanks @laktak! With that change, line mode as part of all mode is behaving exactly the way I'd hoped.
