### ISSUE TITLE
tmux-extrakto.sh: line 35: fzf: command not found

### ISSUE THREAD

**Issue by oblitum** [laktak/extrakto#14]
I get command not found for fzf even after installing fzf as documented. I don't know the reason this happens for me though, I've created a simple `sample.sh` script with:

```bash
#!/bin/bash

fzf --help
```

When running `./sample.sh`, I get the fzf help just fine.

**Comment by oblitum** [comment]
Hard coding `$HOME/.fzf/bin/fzf` on line 35 circumvents the issue but I wish it to work without a patch.

**Comment by laktak** [comment]
It sounds like fzf added to your `PATH` but tmux is still running with the old one. If that's the case the easiest solution is probably to just restart tmux.

**Comment by oblitum** [comment]
I did restart it, forgot to mention that.

**Comment by laktak** [comment]
I've added an option to set the path to fzf, you can change it with:

```
set -g @extrakto_fzf_tool "fzf"
```

**Comment by oblitum** [comment]
@laktak great, this works for me 😉
