### ISSUE TITLE
Feature request: open

### ISSUE THREAD

**Issue by oblitum** [laktak/extrakto#15]
Loving this plugin. I wish, besides providing insertion and copy, that it provided open. It would work for files, URLs etc. There could be a simple configuration for the opening command, for example, for me, simply setting up [gio](https://developer.gnome.org/gio/stable/gio.html)` open <text selection>` as the command would work for most files and URLs.

**Comment by laktak** [comment]
Sounds like a good idea. I'll look into it ... unless you'd like to do a PR?

**Comment by maximbaz** [comment]
Nice idea, my only request: please don't hardcode the use of `gio`, use the standard wrapper `xdg-open` that is available everywhere - it will use `gio` itself if it is appropriate. 

This is an inspiring comment: https://github.com/github/hub/issues/1473#issuecomment-303656214

**Comment by laktak** [comment]
I've added an `extrakto_custom_tool` option that you can set to the tool of your choice:

```
set -g @extrakto_custom_tool "xdg-open"
```

If this works OK we can add this and `open` (mac) as defaults.

**Comment by oblitum** [comment]
ah... I was about to offer a pull request. If there's anything to use there yet, feel free to pick https://github.com/oblitum/extrakto/tree/open-functionality.

**Comment by maximbaz** [comment]
Awesome stuff guys!

Plain `xdg-open` is almost perfect, but it produces some unnecessary output in STDOUT that I don't need to see. I suggest this as a default for Linux:

```
set -g @extrakto_custom_tool "xdg-open >/dev/null"
```

**Comment by laktak** [comment]
@oblitum sorry - so why didn't you say so? I'd definitely add your defaults!

```
+if [ -z "$open_tool" ]; then
+  case "`uname`" in
+    'Linux') open_tool='xdg-open >/dev/null' ;;
+    'Darwin') open_tool='open' ;;
+    *) ;;
+  esac
+fi
```

**Comment by oblitum** [comment]
@laktak ¯\_(ツ)_/¯

**Comment by maximbaz** [comment]
@laktak why require configuration in the first place, why not just have the defaults always enabled?

**Comment by laktak** [comment]
@maximbaz I think this could use some more testing before enabling it by default. It now appears to work with relative paths. Can you guys test on your systems?

**Comment by oblitum** [comment]
@laktak yes, it wasn't working when current working directory wasn't `~`, it's working now (also for `../foo.txt`, etc).

**Comment by maximbaz** [comment]
It happens that I don't have a GUI file manager installed, and thus I have no association with file paths at all on my system... so I all can say is that opening URLs works really well 😄

**Comment by laktak** [comment]
In that case @oblitum what are you using? I also have no gui apps besides firefox (but xdg-open opens json files there ;)

**Comment by oblitum** [comment]
I'm just testing with `.txt` files, I have GVim associated by default to open such files in the MIME database.

**Comment by maximbaz** [comment]
I would say that it seems to work good right now, and enabling this functionality by default will make more people using and testing this, and if something is not working correctly I'm sure we will hear about this soon :)

**Comment by laktak** [comment]
OK, you are probably right ;) It's now set as default.

**Comment by oblitum** [comment]
@laktak nice. IMO it looks a bit inconsistent to have both `""` (for `clip_tool`) and `"auto"` (`open_tool`) to mean the same: to use internal defaults.

**Comment by laktak** [comment]
@oblitum fixed
