### ISSUE TITLE
Feature request: open with $EDITOR

### ISSUE THREAD

**Issue by x4121** [laktak/extrakto#20]
This request is quite similar to #15 and comes from https://github.com/tmux-plugins/tmux-open.
The idea is to split between "I want to open this folder/URL/file in the system default" and "I want to edit this file in $EDITOR inside tmux".

Would this feature be of interest/accepted? What would be an appropriate keybinding (tmux-open used 'o' for xdg-open and 'ctrl-o' for $EDITOR), maybe 'ctrl-shift-o'?

Thanks in advance, already love this plugin :)

**Comment by laktak** [comment]
Sounds like a useful idea. But to be sure I understand you correctly - 'open with $EDITOR' (maybe ctrl-e = edit) would just send `$EDITOR <SELECTION>\n` to the terminal?

**Comment by x4121** [comment]
I guess so, I haven't looked at the implementation of tmux-open honestly. But you understood the idea correctly, it's some kind of shortcut for typing the editor name, inserting the file name from extrakto and pressing return.

I thought about ctrl-e at first, but it's a bit hard to type (at least as a vim user, maybe emacs users are more trained in that :wink: )

**Comment by x4121** [comment]
This seems to be solvable in a few lines, but I can't get `tmux send-keys` to write to the terminal... maybe it's writing it to the temporary pane? Maybe I'm just too tired :sweat_smile:

**Comment by laktak** [comment]
Thanks for the PR!

**Comment by joiharalds** [comment]
I have set $EDITOR=nvim in .bashrc but still extrakto always executes vi -- $value.

Running tmux 3.2a, neovim 0.5.0, ubuntu 20.04

Minimal .tmux.conf which reproduces problem

`# Extracto fuzzy match in pane`
`set -g @plugin 'laktak/extrakto'`

`# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)`
`run -b '~/.tmux/plugins/tpm/tpm'`

What more info do you need to help with this problem or am I just missing something simple?
