### ISSUE TITLE
Exclude box drawing (TUI) from matches

### ISSUE THREAD

**Issue by oblitum** [laktak/extrakto#22]
For example, URL matching for `|http://google.com` is returning it as `|http://google.com`, without removing the `|`.

**Comment by laktak** [comment]
This should work better now (for both url and word filters).

**Comment by oblitum** [comment]
Actually, I had an issue with the `│`, not `|`. It's a longer bar used in TUI for creating windows...

**Comment by oblitum** [comment]
http://www.fileformat.info/info/unicode/char/2502/index.htm

**Comment by laktak** [comment]
I'd rather not add unicode characters to this list. Maybe this could be solved by filtering for [unicode blocks](http://www.fileformat.info/info/unicode/block/index.htm) - like excluding U+2000 to U+2BFF?

(as a workaround for now you can switch the filter to url)

**Comment by oblitum** [comment]
Filtering only URLs doesn't sound like a good idea... I use it both for words and URLs. Excluding UNICODE only makes sense at the start of the URLs, because it can be part of both words and URLs.

**Comment by laktak** [comment]
I only meant to exclude the specified blocks, not all of unicode.

**Comment by oblitum** [comment]
Ah ok, I guess it's reasonable to remove box drawing stuff, because of TUIs.

**Comment by laktak** [comment]
@oblitum please test with master

**Comment by oblitum** [comment]
@laktak OK just fine, issue link opened from neomutt, from where this started 😁
