### ISSUE TITLE
Exits with error

### ISSUE THREAD

**Issue by john-kurkowski** [laktak/extrakto#25]
Neat plugin! I like anything that interops with fzf.

If I open this plugin's fzf window and change my mind, hit Ctrl-C, the window remains open with an error message.

```sh
error: unable to extract - check/report errors above
You can also set the fzf path in options (see readme).
```

There are no errors "above." This is not an error situation. I just don't want to extract anything.

Workaround isn't too bad, but it's an extra keypress: press Enter, and the error window closes.

**Comment by maximbaz** [comment]
While this is being investigated, as a workaround you can use <kbd>Esc</kbd> instead of <kbd>Ctrl+C</kbd> to close fzf when you change your mind 🙂

**Comment by laktak** [comment]
Thanks, I've added `ctrl-c` to cancel fzf like `esc`.
