### ISSUE TITLE
Using tmux pane as the split mechanism is problematic

### ISSUE THREAD

**Issue by DanCardin** [laktak/extrakto#28]
A typical thing I do is have a number of splits in a pane, zoom (prefix + z) into a split and do stuff. Using extrakto in this context takes you out of the zoom and makes the pane (understandably) revert to the unzoomed view.

It may be that there's nothing to do about this. which I suppose is fine because I can't think of a direct way to fix this; just figured I'd mention it in case something came to mind

**Comment by laktak** [comment]
Yes, I had this issue myself a few times.

I think it should be possible to save and restore the window layout.

```
layout=$(tmux display-message -p "#{window_layout}")
tmux select-layout "$layout"
```

The only problem is that this has to happen before extrakto starts and after it exits so we'll have to add a wrapper somewhere...

**Comment by prashantkhurana** [comment]
Is there any solution or workaround for this (other than fixing the bug :) ?

**Comment by laktak** [comment]
We could open extrakto in a new window if you open it while zoomed. Would that help?

**Comment by laktak** [comment]
This will be solved once tmux popups are supported. See #40
