### ISSUE TITLE
Quiting fzf with <c-d> yields error message.

### ISSUE THREAD

**Issue by stagnation** [laktak/extrakto#29]
This error message seems to be meant for when fzf is not installed, not for when fzf exists with a non-zero exit code. I'm used to <c-d> to close fzf and would like it to work just like if <esc> was pressed.

```
error: unable to extract - check/report errors above
You can also set the fzf path in options (see readme)
```

<prefix> <tab> <c-d> to reproduce for me.
with a very sparse tmux.conf

```
set-option -g prefix C-Space

set -g @plugin 'laktak/extrakto'

run '~/.tmux/plugins/tpm/tpm'
```

**Comment by laktak** [comment]
Thanks. I think this is the same error as #32
