### ISSUE TITLE
ctrl-l for grab-area toggle isn't very much friendly to tmux navigation

### ISSUE THREAD

**Issue by oblitum** [laktak/extrakto#31]
It's very common to bind `ctrl-hjkl` for tmux window navigation, see [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator) for example, so `ctrl-l` for grab-area toggle conflicts with it and simply doesn't work. I'm currently using `ctrl-g` instead (`g` from "grab"), with a local patch.

**Comment by cpakkala** [comment]
Agreed.  It would be nice if we could override the keybindings using tmux options.

**Comment by laktak** [comment]
I can no longer reproduce this issue. `ctrl-l` works to toggle even with the navigator active.

**Comment by oblitum** [comment]
I just updated extrakto to upstream and behavior is still the same. Regardless whether you can reproduce or not, I still think `ctrl-l` isn't a good hard-coded key binding to have because it's too common to be used for navigation.

**Comment by laktak** [comment]
OK, since I don't plan on implementing configurable keybindings (PR anyone?) I've change it to `ctrl-g` for now.
