### ISSUE TITLE
Completion mode

### ISSUE THREAD

**Issue by twang817** [laktak/extrakto#35]
It would be nice to be able to use extrakto to complete the word the command line.

For example, if I have on the command line:

```
> git add src/t
```

If, at this time, I hit `prefix + tab`, I would like for extrakto to start the fzf with `src/t`.  At this point, I should be able to continue typing or event modify the command.  Once I select the line I want, I should be able to hit `tab` and it will replace word on the command-line.

**Comment by laktak** [comment]
Yes this sounds useful. It may need a different keybinding though to avoid conflicts if you just want to copy something.

I don't plan to implement this but you can submit a PR.
