### ISSUE TITLE
Searching across more than just the current pane?

### ISSUE THREAD

**Issue by chrismetcalf** [laktak/extrakto#36]
Sometimes I want to search within a different pane than I'm currently in - is there an option to do that or could there be?

**Comment by laktak** [comment]
Press `ctrl-l` to toggle the grab area to `[window full]`. You should see this in the header:

```
tab=insert, enter=copy, ctrl-o=open, ctrl-e=edit, ctrl-f=toggle filter [word], ctrl-l=grab area [full]
```
