### ISSUE TITLE
Feature request :: tmux popups

### ISSUE THREAD

**Issue by lcrockett** [laktak/extrakto#40]
Any chance it will be expanded in the future to support tmux's (+3.2) new popup functonality ? It would be nice if instead of an additional pane, the results of `extrakto` would open in a separate popup.

See also other resources related to this feature:
- https://github.com/tmux/tmux/issues/1842
- https://github.com/kevinhwang91/fzf-tmux-script

I've tried playing around with a alternative key binding to see if I could get it working:
`bind-key A display-popup -d '#{pane_current_path}' -E -K -R "$HOME/.tmux/plugins/extrakto/scripts/tmux-extrakto.sh" -h 90% -w 90% -yC -xC`

This works to some degree, however it looks like it has issues pulling the contents of the current pane. That can possible be reproduced by repeatedly hitting `ctrl-g` while within the popup window. You'll be able to see the error popup in the background: `can't find pane !`

By any chance, is there any popup 'roadmap' ?

**Comment by laktak** [comment]
Thanks for the heads up! I will definitely look at this once tmux 3.2 is released.

**Comment by laktak** [comment]
extrakto will now use popups if you have the tmux beta with popup support. Please give it a try.

**Comment by carlocab** [comment]
@laktak The popup works great; thanks for this. Do you mind including options allowing configuration of the popup size?

I can work on a PR for that if you prefer.

**Comment by laktak** [comment]
@carlocab yes, that's a good idea. I don't have tmux 3.2 as a daily driver so please go for it.

We already have `@extrakto_split_size` so I'd suggest using `@extrakto_popup_size` that contains both values separated by a comma like `90%, 90%`

**Comment by carlocab** [comment]
Sure, let me find some time over the next week or so to look at it.

tmux also lets you choose the popup window position [[Ref](http://man.openbsd.org/OpenBSD-current/man1/tmux.1#display-popup)]. Does `@extrakto_popup_position` work for that for you?

**Comment by lcrockett** [comment]
This works as intended and is a great improvement over the split pane approach ! Using `tmux next-3.2` here @ MacOS Catalina.

Thank you for this superb change !

**Comment by laur89** [comment]
Can the issue be closed now?

**Comment by laktak** [comment]
> Thank you for this superb change !

That goes to @carlocab as well for adding the customizations!
