### ISSUE TITLE
Wonderful plugin, over come remain-on-exit?

### ISSUE THREAD

**Issue by nodswal** [laktak/extrakto#41]
I wish I knew of this tmux plugin earlier.  Fantastic work!  I will be advertising this for you where I can make the suggestion. :)

My co worker is all standard stuff, I think this is going to be the one plugin I can get him to install.  so much easier the grabbing the mouse to copy and paste something that is to long or complicated to type. 

Support request:
I use the dead pane option in tmux, it keeps ssh failures or disconnects from closing a window so I know that it disconnected.  Is there an option that I can set to force the dead pane closed when using your amazing plugin. 

Tmux 3.1b
bind-key R respawn-pane
set-option -g remain-on-exit on

is what I have for the window to stay open, and it allows me to reconnect to a server. It also keeps the extrakto window pane open after using it but would like it to close out if possible.  Thank you so much for your time.

**Comment by laktak** [comment]
I think you should use `set-option remain-on-exit on` (without `-g`) only for the windows where you need it. You could modify your bind key for extrakto (to turn off remain-on-exit) as well but try this first.

**Comment by nodswal** [comment]
Very cool, thank you so much for the reply, I will look into binding tab to also turn off remain-on-exit for that window.  I ssh a lot so pretty much want it on all except this window.

**Comment by laktak** [comment]
Glad I could help.
