### ISSUE TITLE
Fetch content prior to opening split

### ISSUE THREAD

**Issue by laur89** [laktak/extrakto#46]
As-is:
Upon launching extrakto (`prefix+Tab`), a split-pane is opened, in the bottom by default.
The contents this new split is covering in the pane will be excluded from the result.

To-be:
Fetch the contents into the script _before_ opening the extrakto split, so the contents this new split covers would be included in results.

**Comment by laktak** [comment]
Thank you for the input. I will try to fix this when we add popups #40 once tmux 3.2 is released.

**Comment by laktak** [comment]
I looked at it but this is not trivial to solve because the content is gathered after we open the split and each time the user changes the grab area.

I don't think it is worth to invest time in this because tmux with popups will solve the problem. If you have the beta please give it a try.
