### ISSUE TITLE
Key binding is broken

### ISSUE THREAD

**Issue by Xeite** [laktak/extrakto#54]
Hi it's really great plugin that I always imagine. Thanks!

But I found on current head(6d953e7b7ac5cb390aac34ad63be6e8612078606), no key is working now.

When I enter "enter, tab, etc", nothing happened and tmux pane is disappear silently. 
 
Although I did not bisect exact commit, I confirmed that
afc7df1f05275595eb6db2a96f93cfe781b3667b is working as expected and suspect there's something wrong between the commits.

My env
- tmux 3.1b
- zsh 5.7.1
- osx catalina

Thanks.

**Comment by laktak** [comment]
We added "preserve fzf query" in #49 - I guess that could be causing the problem.

What does `fzf --version` say?

**Comment by Xeite** [comment]
extrakto$ fzf --version
0.22.0 (e2ae1b2)

Yes I confirmed that the commit is broken.

**Comment by laktak** [comment]
I've downgraded to fzf 0.22.0 but I'm not able to reproduce your issue.

> Yes I confirmed that the commit is broken.

So a375e9a still works for you but 405394c does not?

What version of bash do you have? Is it the one shipped with MacOS (3.2)?

**Comment by Xeite** [comment]
Yes, `a375e9a` works but not `405394c`

I use zsh. 
```
extrakto$ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

**Comment by laktak** [comment]
Yes, but the extrakto scripts use bash. What does `/usr/bin/env bash --version` say?

**Comment by Xeite** [comment]
Here it is.
```
BigBirdMessageBus$ /usr/bin/env bash --version                                                                                                        GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by laktak** [comment]
That's a strange output but I guess it's 

> GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
> Copyright (C) 2007 Free Software Foundation, Inc.

Did you install tmux with homebrew? Then you can do `brew install bash` to get version 5.0. Apple does not distribute a newer Bash because of the license.

**Comment by Xeite** [comment]
Sorry I wrongly copied
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```
It was as you expected

```
$ /usr/bin/env bash --version
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

And now that I upgraded bash, it works! I did not expect it's due to the shell version :) 

Thanks a lot
