### ISSUE TITLE
Insert/copy not working on Apple M1

### ISSUE THREAD

**Issue by betoharres** [laktak/extrakto#55]
Hello, first of all, I love this plugin, thanks for the awesome job!
I just got a MacBook Air M1, and after setting up tmux I was not being able to copy/insert the results that show up. I already tried to use the HEAD version of tmux as described in this README but I got the same behavior.

The plugin looks like it's working, everything show up as normal, it's only when I select the value from the list by hitting Tab or Enter that nothing happens. My clipboard remains untouched with the previous text I've selected in the past. 

I do have python@3.9.1 running and the Terminal.app is running under Rosetta 2, and I've tested the `pbcopy` command separately and it does work.

Just a side note: when using Vim, I had problems with ultisnips throwing python errors almost every time I entered in INSERT mode; I'm still not sure what was and my only solution was to remove the plugin for now. 

EDIT: just to add to my side note, I've installed my dev env a few times on linux in the past months using this plugin and I never had a problem before, it always worked!
EDIT2: I'm using zsh, not bash :)
Any suggestions on what should I do? Thanks!

**Comment by laktak** [comment]
What version of bash do you have installed? It will not work with the one from OSX, you need 5+ from homebrew.

**Comment by betoharres** [comment]
@laktak you're right! Thanks a lot and sorry for misunderstanding the README; everything is working now!

**Comment by laktak** [comment]
No problem :) I've added a version check.
