### ISSUE TITLE
Can I work with a substring of the fuzzy match?

### ISSUE THREAD

**Issue by windowsrefund** [laktak/extrakto#56]
First off, I love this plugin! Thank you.

So let's say I've got a long URL like http://thisissomesubdomain.example.com in my pane. Now I want to do a DNS lookup on it or whatever so I know I don't want the protocol. If I fuzzy match and press tab, I get the whole string. Is there a way for me to narrow things down so I don't have to paste and then edit my command line before pressing enter?

**Comment by laktak** [comment]
Thanks!

We have filters that you can toggle with ctrl-f but nothing like what you are asking for. Is this something that you need often?

**Comment by systemmonkey42** [comment]
I think it would make sense to include URL's multiple times..
* Once with the prefix `(http|https|ftp|ssh|sftp)://` etc
* Once without
* Maybe even again with only the hostname.

Another option is an additional hot key (I use <kbd>ctrl-a</kbd>) which does the following;

```
     ctrl-a)
		tput cup 99 0
		read -p "Selection > " -eri "$text" text
                tmux set-buffer -- "$text"
                tmux paste-buffer -t $trigger_pane
		return 0
		;;
```
This display the selected text on a line of its own, allows it to be edited (using standard readline input keys, usually the same as your bash default) and pastes the modified text. (remember to include the hotkey `ctrl-a` in the list of expected keys.)

I've found this handy because I often want to select text with spaces (eg, filenames with spaces), so its often easier to select the entire line (in line mode) and edit it.

The URL problem also applies to shell variables...
For example; after `cat scripts/extrakto.sh`, pressing prefix+Tab and searching for `extrakto_opt` gives the following result;

```
  @extrakto_popup_position                                                                                    
  @extrakto_default_opt                                                                                       
  @extrakto_open_tool                                                                                         
  header/:eo:/$extrakto_opt                                                                                   
  extrakto_opt=$                                                                                              
  extrakto_opt='path/url                                                                                      
  extrakto_opt='lines                                                                                         
  extrakto_opt='word                                                                                          
 $extrakto_opt                                                                                               
  enter=insert, ctrl-c=copy, ctrl-o=open, ctrl-e=edit, ctrl-f=toggle filter [word], ctrl-g=grab area [full]   
> extrakto_opt                                                                                                
```
Searching for 'extrakto_opt' finds everything EXCEPT the word 'extrakto_opt'.... despite it being one of the most common words on the page.

Splitting on '$', '=' and presenting all options would help.
* extrakto_opt
* $extrakto_opt
* extrakto_opt='line'
* extrakto_opt='word'
etc.

And don't get me started on quote handling.   If a string is in quotes, include a copy of the entire string, as well as the individual words..  Showing `extrakto_opt='line` is the least useful result.

Aside from that, I "discovered" extrakto a couple of days ago, and already wouldn't want to live without it.
Thanks for the great work.

**Comment by laktak** [comment]
I think including the result in multiple variants is a great idea! And you are right, $ and = should split.

Not a big fan on manual editing though ;)

More filers would be useful but the filter toggle is not great. It was OK when there were only two filters but it is already mildly annoying with three.

I am considering changing it two a two-step mode. First you fzf-select the line you need and then you get the results from all filters (file, quoted strings, etc.) for that line in another fzf. The word mode would stay the default though because IMO it is still the most common option. Maybe I'll test that for a while ...

**Comment by laktak** [comment]
Here is something to experiment with: https://github.com/laktak/extrakto/tree/twostep

**Comment by windowsrefund** [comment]
This "two-step" mode sounds very promising and I'm happy others are eager to explore the utility behind the idea as well. Please just don't forget to make the "ctrl-k" binding configurable though as I personally use that binding to drive my window manager and would want to rebind it. Thanks again. Looking forward to seeing where this goes :)

**Comment by laktak** [comment]
Yes, it allows you to configure the binding (see readme) - I wanted something quicker to type by default.

It currently does domain extraction and quote matching... let me know if it works for you.

**Comment by windowsrefund** [comment]
I don't think it's working as I can't seem to progress past the ctrl-k stage. After I installed manually from the branch, I did the following in order to test

```
echo https://github.com/laktak/extrakto/tree/twostep
prefix-<tab>
ctrl-k
two<enter>
```
This fuzzy selects the URL I echo'd but I no longer see the ctrl-f option 

My menu looks like this:

tab=insert, enter=copy, ctrl-k=two-step, ctrl-o=open, ctrl-e=edit, ctrl-g=grab area [full]

**Comment by laktak** [comment]
After your last step you should see the results from the line you selected passed through all filters.

I've updated it so that the UI now says
```
[two-step] select input for filters
```
for the first step and then:
```
[two-step] now choose from a filter result for your selection:
```

**Comment by systemmonkey42** [comment]
I think I understand what is happening with the <kbd>ctrl-f</kbd> filter flag....

* The first mode uses the equivalent of the 'word' filter.
* Pressing <kbd>ctrl-k</kbd> pops you into "line" filter
* Selecting a line (while in <kbd>ctrl-k</kbd>) used that line as input and applies all(?) filters to generate a range of outputs which are all presented for selection.

I'm not sure how to select a complete line though...

I'm leaning towards liking the idea of simply having *more* filters.  I work better when I bind a key (or chord) to a
specific action (having to jump through modes guarantees I'll forget to use the functionality).

To that end, I'm moving down the path of making the "filter" a parameter, so I can bind keys to filters. (like prefix <kbd>ctrl-u</kbd> for jumping straight into url filter mode.

My plan is then to add many filters. (eg, ones which understand git-log format, ones which understand filenames with spaces and can automatically apply quoting, and I'm working on a way to recognise the _bash prompt_ and strip it automatically from every line before filtering as well as supporing multiple selections (though ordering is always a problem).)

I'm not sure my work will mesh with how you plan on progressing with extrakto, but I certainly thank you for the inspiration.

**Comment by systemmonkey42** [comment]
As an aside, consider including the fzf "print query" option.

After pressing 'ctrl-k', the print-query ensures the characters typed so far are output (on a line, before the 'ctrl-k'), so you can automatically re-add the query when re-entering fzf.

**Comment by windowsrefund** [comment]
This is still not working (as expected?) with the updated branch

```echo http://example.com
prefix-<tab>
ctrl-k
ex
```

In the displayed list, I only see the entire string of http://example.com

**Comment by systemmonkey42** [comment]
> This is still not working (as expected?)

Steps include
1. prefix <kbd>Tab</kbd>
2. <kbd>ctrl-k</kbd>
3. ex (select line containing URL)
4. <kbd>ctrl-c</kbd>
5. displayed list will now include original url, and url without http://prefix.

If you stop at step 3, you havent completed the "two step" process.

**Comment by laktak** [comment]
@systemmonkey42 why <kbd>ctrl-c</kbd>? It should be <kbd>enter</kbd>

@windowsrefund systemmonkey42 is right unless you pressed enter and there is still no result? However I'm currently updating it so you can select the filter as well as the result - I'll let you know when the new test is ready.

**Comment by laktak** [comment]
> I'm leaning towards liking the idea of simply having _more_ filters. I work better when I bind a key (or chord) to a
> specific action (having to jump through modes guarantees I'll forget to use the functionality).
> 
> To that end, I'm moving down the path of making the "filter" a parameter, so I can bind keys to filters. (like prefix ctrl-u for jumping straight into url filter mode.
> 
> My plan is then to add many filters. (eg, ones which understand git-log format, ones which understand filenames with spaces and can automatically apply quoting, and I'm working on a way to recognise the _bash prompt_ and strip it automatically from every line before filtering as well as supporing multiple selections (though ordering is always a problem).)
> 
> I'm not sure my work will mesh with how you plan on progressing with extrakto, but I certainly thank you for the inspiration.

I'm open to more filters - that was the reason I created this test branch. However I'm not sure what's the best way to select the filter. I want to avoid having to bind each filter to a key combination. I'll try to improve this with the next iteration.

**Comment by systemmonkey42** [comment]
> @systemmonkey42 why ctrl-c? It should be enter

Ah, my mistake.  You are re-using the binding for "copy".  I moved copy from "enter" to "ctrl-c", so i could use "enter" to select the line. (In place of <tab>).  Pressing tab broke my muscle memory (I use 'fzf' in a popup for many things, and enter is always the key to finish.)

**Comment by windowsrefund** [comment]
Thanks for all the feedback. I guess it just felt natural to try and capture the thing of interest before doing something with it. Of course, I'm fortunate enough to not have any muscle-memory baked in at this point which I'd need to alter so I'll be standing by....

Thanks again

**Comment by laktak** [comment]
I've replaced the two-step mode as it was too confusing.

You can now define your own filters (see readme) and toggle to show word, all or line results with `ctrl-f`. Please give it a try.

**Comment by windowsrefund** [comment]
Work nicely! This is great :+1:

**Comment by laktak** [comment]
Glad you like it and thanks for the feedback! I like this way better than the old filters.
