### ISSUE TITLE
Suggestion for setting @extrakto_key to '' does not work.

### ISSUE THREAD

**Issue by systemmonkey42** [laktak/extrakto#61]
> The key binding to start. If you have any special requirements (like a custom key table) set this to '' and define a binding in your .tmux.conf. See extrakto.tmux for a sample.

This does not work as described.

The only workaround I've found is to unbind the key afterwards, which is too late as its already removed my existing tab binding.

**Comment by laktak** [comment]
Yes, this must have stopped working when we added the helper script for the configuration. 

Please try `set -g @extrakto_key "none"`

**Comment by systemmonkey42** [comment]
> Please try `set -g @extrakto_key "none"`

Can you make it case-insensitive? (Just in case..)
```
if [[ "${extrakto_key,,}" != none ]]; then
    tmux bind-key ${extrakto_key} run-shell "\"$extrakto_open\" \"#{pane_id}\""
fi
```

**Comment by laktak** [comment]
OK, I'm not overly sensitive on that ;-)
