### ISSUE TITLE
Add a flag to provide fzf options

### ISSUE THREAD

**Issue by cibinmathew** [laktak/extrakto#65]
Add env variable to provide fzf options
eg: `set -g @extrakto_fzf_options "--preview 'cat {}'"`

**Comment by laktak** [comment]
While I haven't tested this you should be able to set `@extrakto_fzf_tool` to "fzf --preview 'cat {}'".

**Comment by cibinmathew** [comment]
This didnt work because of it checking for the fzf path with the entire string I guess. I tried with a new variable but it failed in picking it.

**Comment by laktak** [comment]
Yes, it fails because bash expands `'` in a strange way.

You can put `fzf --preview 'cat {}' "$@"` into a script file and then point `@extrakto_fzf_tool` to it. Not sure if that is what you want but it can preview absolute paths.

**Comment by laktak** [comment]
Closing as well.
