### ISSUE TITLE
word filter should split on commas

### ISSUE THREAD

**Issue by laur89** [laktak/extrakto#67]
`word` filter currently doesn't split on commas. Eg if there is line like `users:(("node",pid=1454441,fd=22))`, then word filter would extract `1454441,fd`; would expect those 2 values to be split on comma.

**Comment by laktak** [comment]
Yes, I think that makes sense. I will update the defaults.

**Comment by laktak** [comment]
Updated. Note that you won't see `fd` as it is too short to be included in the result (by default).

**Comment by laktak** [comment]
@laur89 I reverted the change because it no longer allowed formatted numbers to be extracted. You can still make it work the way you want - see the sample in https://github.com/laktak/extrakto/blob/master/extrakto.conf
