### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by seqizz** [laktak/extrakto#71]
Hi, thanks for this plugin.

Recently the plugin stopped working (nothing happens after ctrl-b <tab> anymore). I can't remember changing something, except regular system updates. I'm not sure how can I supply information to debug this though. Installed via tpm:

Bash: `GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)`
Tmux: `tmux 3.1c`
Fzf: `0.22.0`

**Comment by laktak** [comment]
run `tmux list-keys|grep extrakto`

You should see an entry like:
```
bind-key    -T prefix       Tab                  run-shell "\"/home/spark/.tools/pkg/tmux-extrakto/scripts/open.sh\" \"#{pane_id}\""
```

Please attach your tmux.conf and I'll check if I can find anything.

**Comment by seqizz** [comment]
It didn't show anything, meaning my environment was fubar. I've just wiped my plugins folder and re-installed all. Looks like I somehow lost executable bit on some scripts of tpm. Sorry for the noise and thanks again.

**Comment by betoharres** [comment]
same thing happened to me so I had to reinstall my plugins to make it work again
