### ISSUE TITLE
How to make the default filter as "lines" ?

### ISSUE THREAD

**Issue by vnea** [laktak/extrakto#72]
Hello,

In my tmux conf, I had this line to make the default filter as "lines":
```
set -g @extrakto_default_opt "lines"
```

I updated the plugin and now this setting does not work anymore.

In the documentation it is said that this option has been removed in favor of the "new filter mode":
![image](https://user-images.githubusercontent.com/10775422/114285380-f7c9e200-9a56-11eb-9964-13b660ffd88e.png)

But I don't really understand what is this new filter mode.

How can I make "lines" as the default filter mode with the new version (git tag is `de8ac3e`) ?

**Comment by jtroo** [comment]
Seems like [this section of the README](https://github.com/laktak/extrakto#custom-filters) is what you're looking for.

My guess is the first option in the [extrakto.conf](https://github.com/laktak/extrakto/blob/master/extrakto.conf) file will be the default.

**Comment by laktak** [comment]
I removed this setting when we changed the filter because while 'lines' would still be valid 'path/url' would not.

For now you can't change the default. If you'd like this feature back please submit a PR. The option should be called `@extrako_startup_filter`, values `word`, `line`, `all`.

**Comment by vnea** [comment]
I understand, thank you.

As a workaround for the moment, I changed the local source code to use the **line** mode by default.

> For now you can't change the default. If you'd like this feature back please submit a PR. The option should be called @extrako_startup_filter, values word, line, all.
Maybe one day, if i am motivated :D.
