### ISSUE TITLE
respect FZF_DEFAULT_OPTS

### ISSUE THREAD

**Issue by jackieli-tes** [laktak/extrakto#78]
I find this one tricky.

I have my colour scheme for FZF stored in FZF_DEFAULT_OPTS. It's synced with base16-shell so I can have one command to switch the colour scheme for the terminal, vim & FZF.

However when I tried to configure extrakto with:

```
set -g @extrakto_fzf_tool "$HOME/.fzf/bin/fzf $FZF_DEFAULT_OPTS"
```

It just didn't work. After some digging I realised I started tmux directly with a keybinding in i3. So that must have skipped my .zshrc eval because it's done after tmux is started?

anyway, I find that the easiest way for me to hack this is just to add `$FZF_DEFAULT_OPTS` when launching the `$fzf_tool` in https://github.com/laktak/extrakto/blob/master/scripts/extrakto.sh#L164

Any better suggestions?

**Comment by laktak** [comment]
I think the easiest option would be to create a fzf-launch script where you first source your .zshrc and then run fzf.

**Comment by jackieli-tes** [comment]
worked around it using a script.
