### ISSUE TITLE
Multiple results (similar to `fzf --multi`)

### ISSUE THREAD

**Issue by yjyao** [laktak/extrakto#79]
This is a feature request to support choosing multiple results. The multiple results should be separated by spaces. Currently extrakto allows only one result per invocation.

## Steps to reproduce

1. in `~/.tmux.conf` add
    ```
    set -g @extrakto_fzf_tool "/path/to/fzf --multi"
    set -g @extrakto_insert_key 'enter'
    ```
1. enter a tmux session with extrakto enabled
2. run `: hello world`
3. trigger extrakto
4. in the extrakto window, move cursor to `hello`
5. press `<tab>` to select
6. move cursor to `world`
7. press `<tab>` to select
8. press `<enter>`to insert

## Expected result

Extrakto inserts `hello world` at cursor position.

## Actual result

Extrakto inserts `world` at cursor position.

## Info

- extrakto version: `f74ec23`
- fzf version: `0.19.0 (9a41fd5)`
- tmux version: `tmux 3.2a`
- python version: `Python 3.9.2`
- bash version: `5.1.8(1)-release`

## Rationale

One of the most common use cases of extrakto is to "retype" file paths. Often users would like to edit several files at a time. For example, after user runs `git status` and sees several files, they might want to edit three of the listed files. Currently user has to trigger extrakto three times to achieve this.

**Comment by laktak** [comment]
Hey, thanks for the suggestion. Sounds like a good idea. I'll look into it when I find some time.

If someone wants to do a PR let us know.

**Comment by laur89** [comment]
> The multiple results should be separated by spaces

Propose it to be separated by configurable separator, defaulting to `space`

**Comment by totallyGreg** [comment]
Another use case for multiple selection:
I want to be able to filter all lines that contain the fuzzy search 'failed'
control-a to select them all (or tab to select individual lines)
and return to copy or insert each of the resulting lines

**Comment by yjyao** [comment]
@totallyGreg i might be jumping to conclusions but that sounds very much like a task better accomplished with `grep`.

**Comment by laktak** [comment]
Hey guys! @benoit-pierre was so kind to do a PR that implements this.

Could you [try it](https://github.com/laktak/extrakto/pull/88), tell him you love it ;) and maybe provide some feedback?
