### ISSUE TITLE
Conditional Key Binding

### ISSUE THREAD

**Issue by kevintraver** [laktak/extrakto#82]
Im trying to do a conditional keybinding like this:

```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

tmux bind-key -n M-f if-shell "$is_vim" "send-keys M-f" "run-shell '$extrakto_open \"#{pane_id}\"'"
```

I was wondering if theres a way to configure this so I can set this key-binding in my regular tmux.conf?

Right now I have to modify the actual `extrakto.tmux` file

**Comment by laktak** [comment]
I'm not sure why you modify `extrakto.tmux`. You can just put this into your `tmux.conf`.

Set `@extrakto_key` to `none` like the readme mentions. You also need to define `extrakto_open` or just replace it with the path to `...extrakto/scripts/open.sh`

**Comment by kevintraver** [comment]
I got it working by setting the path! Works great! Thank you.
