### ISSUE TITLE
Can't edit when not in a shell

### ISSUE THREAD

**Issue by keydon3** [laktak/extrakto#83]
**Context:** cant edit filepath in editor when extract token from tmux pane with neovim
**What happened:** 

- open tmux
- open file file_with_path.txt with filepath in tmux with neovim
- press prefix+tab (call extrakto)
- select filepath, press ctrl+e
- filepath doesnt open in editor, but text is selected in neovim in file_with_path.txt buffer

**What expected:** open ~/.tmux.conf in editor
**Reproduction steps:**
```
$ tmux
$ # add filepath, for example ~/.tmux.conf
$ echo '~/.tmux.conf' > /tmp/file_with_path.txt
$ # open neovim and press ctrl+tab, "tmux", ctrl+e
$ nvim /tmp/file_with_path.txt
```

**Comment by laktak** [comment]
This is not how this feature works though it was not explained very well - I've updated [HELP.md](https://github.com/laktak/extrakto/blob/master/HELP.md).

extrakto will send the command to open the editor to the active pane. This only works if you are in a shell.

Let us know if you have suggestions on how this can be improved.
