### ISSUE TITLE
Path matched terminate on a space, even if the space is escaped.

### ISSUE THREAD

**Issue by systemmonkey42** [laktak/extrakto#84]
When matching a path, shell completion will often result in escaped spaces (in preference to quotes)
eg
```
# ls '/export/datastore/Images/Windows Server/en_window_server_version_20h2_x64_dvd_a<press tab for completion>
# ls /export/datastore/Images/Windows\ Server/en_window_server_version_20h2_x64_dvd_a932282f.iso <expanded result>
/export/datastore/Images/Windows Server/en_window_server_version_20h2_x64_dvd_a932282f.iso
```
Extracto completion will give me
 `/export/datastore/Images/Windows\`
and
 `Server/en_window_server_version_20h2_x64_dvd_a932282f.iso`
as two separate choices.

Can the function to idenfifying paths keep escaped spaces?  Possibly giving a choice of original escaped path, quoted path, or just the path (just as it does when identifying a quoted string)?

Thanks

**Comment by laktak** [comment]
Did you notice any side effects with your regex? If not, do you want to put it on the wiki?

**Comment by laktak** [comment]
I added it to the wiki: https://github.com/laktak/extrakto/wiki/Custom-Filters
