### ISSUE TITLE
Ctrl-F while python is still processing raises error

### ISSUE THREAD

**Issue by laur89** [laktak/extrakto#89]
If tmux pane has loads of data in the buffer and extracto is loaded, then pressing `ctrl-f` in quick succession causes python logic to throw: https://i.imgur.com/kFqem8i.jpg

**Comment by laktak** [comment]
I can reproduce this but only as a flicker as fzf then shows the correct results.

I wouldn't consider this too much of an issue but if someone wants to investigate I'd be interested in the cause.
