### ISSUE TITLE
Remote Copy via OSC52 setup assistance

### ISSUE THREAD

**Issue by eb0687** [laktak/extrakto#90]
Hi there,

I can not get the remote copy feature to work via the extrakto interface and can not figure out why.

Following the instructions [here](https://github.com/laktak/extrakto/wiki/Remote-Copy-via-OSC52) 

- On the remote machine which I have ssh'd into I created a file called osc52 and pasted the below bash script in it.
```
#!/bin/bash
printf "\033]52;c;$(base64 | tr -d '\r\n')\a"
```
- Moved it to ~/.local/bin
- Made sure it is executable. `chmod +x osc52`
- the example test works as intended and I do see the `hello` text in my local clipboard.
- I do have the below lines in my `tmux.conf` on my local machine
```
set -g set-clipboard on
set -g @extrakto_clip_tool_run "fg"
set -g @extrakto_clip_tool "osc52"
```
I can confirm that the pop up window does have the ssh'd contents, but when hitting `enter` to copy text, nothing appears in my local clipboard. The `Tab to Insert` feature does work though! 

Honestly, I have never heard of osc52 until today and even google'd it thinking I was doing something wrong. Even came across an [article](https://oroques.dev/2020/11/27/vim-osc52.html) saying that for osc52 to work the terminal itself must support it. I luckily use Alacritty which supports osc52 based on the article.

Since I can copy to my local clipboard from the remote machine using `echo hello | osc52` , I am assuming it has something to do with my tmux.conf?

**Comment by laktak** [comment]
Not sure I can help with this. Did you restart/reload your tmux config on the remote machine? Also add a line in osc52 to write to a log file so you can see if it is being invoked.

**Comment by eb0687** [comment]
wait...I thought tmux does not need to be installed on the remote anymore?

or am I mistaken in how this works?

**Comment by laktak** [comment]
You only need this if you run tmux remotely:

> When you run a tmux session via ssh

If you run tmux locally it can copy to the local clipboard anyways.

**Comment by laur89** [comment]
What terminal are you running? Afaik _very_ few terminals implement OSC 52 escape codes.

**Comment by laktak** [comment]
Also see #93
