### ISSUE TITLE
OSC 52 Issue

### ISSUE THREAD

**Issue by hegga** [laktak/extrakto#92]
Hi!

Thanks for an excellent tmux plugin! I use this extensively every day. However, at the moment I am trying to transition to using OSC 52 for remote copying over SSH. 

I use the Kitty terminal, and I have the following in my kitty.conf:
```
clipboard_control   write-clipboard write-primary no-append
```

I have also created a osc52.sh which looks like this:
```
#!/bin/bash
date >> ~/osc52.log
printf "\033]52;c;$(base64 | tr -d '\r\n')\a"
```

The date line is just there for logging purposes so that I know when the script has been executed.

Executing the script like shown below works as a charm and copies the text to my local clipboard over a SSH connection (inside of a tmux session):
```
echo testing | osc52.sh
```

My extrakto config looks like this:
```
set -g @extrakto_clip_tool_run "fg"
set -g @extrakto_clip_tool "osc52.sh"
set -g @extrakto_popup_size "68%,32%"
```

However, if I invoke extrakto by pressing prefix+Tab, selecting the desired text, I seem to end up in a copy/view mode which does not display anything. The logfile of the script shows that is has been run, but nothing has been copied to my clipboard. Can you think of any reason why this is not working?

Thanks again for a excellent piece of software, it really meets my needs.

**Comment by laktak** [comment]
- You are running tmux + extrakto on a server to which you are connected via ssh? 
- In you terminal you only have ssh (no tmux)?
- What do you mean by copy/view mode?
- Did you forget `set -g set-clipboard on`? see [wiki](https://github.com/laktak/extrakto/wiki/Remote-Copy-via-OSC52)

**Comment by hegga** [comment]
1. Yes
2. On my local machine it's just the terminal SSH'ing to the remote machine to a tmux session, yes. (No local tmux session)
3. Please have a look at the attached screenshot, here I have initiated extrakto and selected some text for copying, and then this happens. The script is executed, but nothing is copied to my clipboard.
<img width="1676" alt="Screenshot 2022-06-30 at 14 26 03" src="https://user-images.githubusercontent.com/49037/176676893-b02912da-3a9d-4dc4-9083-773308ce7623.png">
4. No, this is set in my .tmux.conf, and tmux itself says that set-clipboard is enabled. 
```
❯ tmux show -s set-clipboard
set-clipboard on
```

Running tmux version 3.3a
```
❯ tmux -V
tmux 3.3a
```

**Comment by laktak** [comment]
That looks very strange indeed. Not sure how/why you get into this mode. Maybe some conflicting tmux options like remain-on-exit?

Please let us know if you find the reason/solution.

**Comment by hegga** [comment]
@laktak Thanks for you feedback, I'm still investigating this issue. During this, I noticed the `-w` option for the tmux `set-buffer` command, are you aware of it? It seems to implement support for OSC 52 natively into `set-buffer`.
