### ISSUE TITLE
Is it possible to extract only based on a filter?

### ISSUE THREAD

**Issue by chauncey-garrett** [laktak/extrakto#96]
Could we set a keybinding to extract on only a single filter or subset of filters? 

e.g., say I wanted to reproduce the functionality of https://github.com/tmux-plugins/tmux-urlview: I'd set `prefix-u` to use `extrakto` to filter for only urls then I could either yank the url to clipboard or open it in my browser.

**Comment by laktak** [comment]
At the moment no - it would require several changes to support this.

You can set the "all" mode to be the default so you'll have the url in the list when you start.

**Comment by marcdeop** [comment]
I know this is closed but I have a working prototype for this built on top of #103 

I personally find this very useful ( I found `extrakto` via using precisely [tmux-urlview](https://github.com/tmux-plugins/tmux-urlview)

@laktak let me know if you would like me to commit on top of #103 or if I should open a different PR in the future
