### ISSUE TITLE
[feature request] please keep the colors as fuzzback does

### ISSUE THREAD

**Issue by nkh** [laktak/extrakto#98]

**Comment by laktak** [comment]
Not sure what you are asking. Please provide some information.

**Comment by nkh** [comment]
if the text in the terminal has colors, don't show it without when making  selection, it makes it much more difficult to locate what one wants to select. IE: it's disruptive and bad UX.

**Comment by laktak** [comment]
Thanks for the feedback and while I value your opinion I think it's a bit much to call it a bad UX.

I think it would take quite a bit of effort to implement this. While I'm not really interested in this feature we do accept PRs - though it shouldn't require changing the user defined regex's or place a huge burden on maintenance.
